// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("2024.3.0.1782")]
[assembly: AssemblyFileVersion("2024.3.0.1782")]
[assembly: AssemblyInformationalVersion("2024.3.0.1782")]
