// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("2023.2.1.1441")]
[assembly: AssemblyFileVersion("2023.2.1.1441")]
[assembly: AssemblyInformationalVersion("2023.2.1.1441")]
