// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("2024.0.1.2027")]
[assembly: AssemblyFileVersion("2024.0.1.2027")]
[assembly: AssemblyInformationalVersion("2024.0.1.2027")]
